name: Publish library to NPM & Dockerhub

on:
  release:
    types: [published]

jobs:
  ci_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      
      - name: Install dependencies
        run: npm clean-install
        
      - name: Lint
        run: npm run lint
      
      - name: Test library
        run: npm run test
      
      - name: Build
        run: npm run build
      
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: rtrompier
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            rtrompier/google-home-notifications:latest
            rtrompier/google-home-notifications:${{ github.event.release.tag_name }}
